server:
  port: 8080

spring:
  application:
    name: java-compiler-service

logging:
  level:
    com.webrules.compiler: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
